name: qdk
channels:
  - conda-forge
  - quantum-engineering
dependencies:
  - python=3.9
  - qsharp
  - networkx
  - rdkit
  - pip
  - jupyter
  - pytest
  - ipywidgets
  - ruamel.yaml
  - varname
  - pip:
    - basis_set_exchange
    - jupyter_jsmol
